/* Generated By:JJTree&JavaCC: Do not edit this line. LTLParserConstants.java */
package org.processmining.analysis.ltlchecker.parser;

public interface LTLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int KAS = 9;
  int KATE = 10;
  int KDATE = 11;
  int KEXISTS = 12;
  int KFORALL = 13;
  int KFORMULA = 14;
  int KIN = 15;
  int KNUMBER = 16;
  int KPI = 17;
  int KRENAME = 18;
  int KSET = 19;
  int KSTRING = 20;
  int KSUBFORMULA = 21;
  int INTEGER_LITERAL = 22;
  int REAL_LITERAL = 23;
  int EXPONENT = 24;
  int STRING_LITERAL = 25;
  int DESC_LITERAL = 26;
  int PIID = 27;
  int ATEID = 28;
  int ID = 29;
  int IDENTIFIER = 30;
  int STARTLETTER = 31;
  int LETTER = 32;
  int DIGIT = 33;
  int LPAREN = 34;
  int RPAREN = 35;
  int LBRACE = 36;
  int RBRACE = 37;
  int LBRACKET = 38;
  int RBRACKET = 39;
  int BAR = 40;
  int SEMICOLON = 41;
  int COMMA = 42;
  int DOT = 43;
  int COLON = 44;
  int ASSIGN = 45;
  int GT = 46;
  int LT = 47;
  int PNOT = 48;
  int SLASH = 49;
  int PLUS = 50;
  int MINUS = 51;
  int STAR = 52;
  int EQ = 53;
  int LE = 54;
  int GE = 55;
  int NE = 56;
  int REQ = 57;
  int POR = 58;
  int PAND = 59;
  int PIMPLIES = 60;
  int PBIIMPLIES = 61;
  int LALWAYS = 62;
  int LEVENTUALLY = 63;
  int LNEXTTIME = 64;
  int LUNTIL = 65;
  int URI = 66;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 8>",
    "\"as\"",
    "\"ate\"",
    "\"date\"",
    "\"exists\"",
    "\"forall\"",
    "\"formula\"",
    "\"in\"",
    "\"number\"",
    "\"pi\"",
    "\"rename\"",
    "\"set\"",
    "\"string\"",
    "\"subformula\"",
    "<INTEGER_LITERAL>",
    "<REAL_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<DESC_LITERAL>",
    "<PIID>",
    "<ATEID>",
    "<ID>",
    "<IDENTIFIER>",
    "<STARTLETTER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\":=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"~=\"",
    "\"\\\\/\"",
    "\"/\\\\\"",
    "\"->\"",
    "\"<->\"",
    "\"[]\"",
    "\"<>\"",
    "\"_O\"",
    "\"_U\"",
    "<URI>",
  };

}
